version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: my_postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  tomcat:
    image: tomcat:latest
    container_name: my_tomcat
    ports:
      - "8080:8080"
    volumes:
      - ./target/RestTemplate-1.0.war:/usr/local/tomcat/webapps/RestTemplate-1.0.war
      - ./conf:/usr/local/tomcat/conf
    depends_on:
      - postgres
    env_file: "conf/.env"



volumes:
  postgres_data: